BEGIN

    FOR X IN (SELECT TABLE_NAME FROM USER_TABLES) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE '||X.TABLE_NAME ||' CASCADE CONSTRAINTS';

END LOOP;
END;

CREATE TABLE TABLE_PAIS(
    ID_PAIS INTEGER PRIMARY KEY,
    NM_PAIS VARCHAR(50)
);

CREATE TABLE TABLE_ESTADO(
    ID_ESTADO INTEGER PRIMARY KEY,
    NM_ESTADO VARCHAR(50)
);

CREATE TABLE TABLE_CIDADE(
    ID_CIDADE INTEGER PRIMARY KEY,
    NM_CIDADE VARCHAR(50)
);

CREATE TABLE TABLE_BAIRRO(
    ID_BAIRRO INTEGER PRIMARY KEY,
    NM_BAIRRO VARCHAR(50)
);

CREATE TABLE TABLE_ENDERECO(
    ID_ENDERECO INTEGER PRIMARY KEY,
    NM_ENDERECO VARCHAR(50)
);